### ISSUE TITLE
Being maintained?

### ISSUE THREAD

**Issue by russel** [jpoirier/rust-rtlsdr#1]
Is this project being maintained or is it now left by the wayside.

I am trying to choose between https://github.com/jpoirier/rust-rtlsdr, https://github.com/adamgreig/rtlsdr-rs and https://github.com/kchmck/rtlsdr_sys.rs as a possible choice for a Rust rewrite of some C code that uses librtlsdr.

**Comment by jpoirier** [comment]
Hey @russel 
No, sorry, I'm not doing any Rust development at the moment but pull requests are always appreciated. 

Note that if you go with the @adamreig wrapper (I recommend that you do) and want to use async IQ data streaming you'll need to add it to the wrapper, which should be a trivial update-you're welcome to copy and paste any code you'd like to from my wrapper.

On a side note, the original rtlsdr c lib is here http://cgit.osmocom.org/rtl-sdr/ but it's rarely updated and I'd encourage you to use and contribute to the updated and maintained fork here https://github.com/librtlsdr/librtlsdr

cheers,
joe

**Comment by russel** [comment]
@jpoirier Thanks for replying. Quite rare that people suggest using competitor products. ;-)

Debian and Fedora both seem to package the original from OsMoCom. It is a pity that the OsMoCom repository is not seeming to take things from the maintained fork. May they are or can be persuaded to. More investigation needed.

**Comment by jpoirier** [comment]
Hi @russel 
I have a Go rtl-sdr wrapper that I actively maintain and the rust and nim wrappers were put together mainly for learning purposes.

Best of luck on the osmocom endeavor.

**Comment by russel** [comment]
Bug report posted about the Debian librtlsdr https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854378

Are you wrapping https://github.com/librtlsdr/librtlsdr ?

**Comment by jpoirier** [comment]
Thanks for doing the bug report. The librtlsdr/librtlsdr library and the one at osmocom are interchangeable and I wrap just the original API at the moment. Disclaimer - I created the https://github.com/librtlsdr/librtlsdr fork.

**Comment by russel** [comment]
Clearly this is a "not inactive" project ;-) so original question answered, answer "yes". So I will close this issue. It is not certain which of the Rust bindings will be used as all three are effectively active and maintained.
